from __future__ import annotations

from typing import Protocol

from meeting_assistant.core.models import Message, Session


class SessionRepository(Protocol):
    def list_sessions(self) -> list[Session]: ...
    def create_session(self, title: str) -> Session: ...
    def get_session(self, session_id: str) -> Session | None: ...
    def set_session_title(self, session_id: str, title: str) -> None: ...
    def set_session_artifacts_slug(self, session_id: str, slug: str) -> None: ...
    def add_message(
        self,
        session_id: str,
        role: str,
        content: str | None,
        file_path: str | None,
        *,
        system_kind: str | None = None,
        recording_llm_instructions: str | None = None,
        recording_whisper_context: str | None = None,
        assistant_kind: str | None = None,
    ) -> Message: ...
    def delete_session(self, session_id: str) -> None: ...
    def list_messages(self, session_id: str) -> list[Message]: ...
    def delete_messages_after_user_with_file(self, session_id: str, file_path: str) -> None: ...
    def get_global_llm_system(self) -> str: ...
    def set_global_llm_system(self, value: str) -> None: ...
    def get_global_whisper_context(self) -> str: ...
    def set_global_whisper_context(self, value: str) -> None: ...
    def get_meeting_output_root(self) -> str: ...
    def set_meeting_output_root(self, value: str) -> None: ...
    def get_ui_language(self) -> str: ...
    def set_ui_language(self, value: str) -> None: ...
    def get_hf_access_token(self) -> str: ...
    def set_hf_access_token(self, value: str) -> None: ...
    def list_session_speakers(self, session_id: str) -> list[tuple[str, str]]: ...
    def replace_session_speakers(self, session_id: str, mapping: dict[str, str]) -> None: ...
    def update_assistant_message_content(
        self, session_id: str, message_id: str, content: str
    ) -> None: ...
    def delete_message(self, session_id: str, message_id: str) -> None: ...
